### PR TITLE
update nan

### PR DESCRIPTION
**Pull request by timoxley**
This updates nan to at least version 1.5.1, enabling compatibility with io.js 1.0.1

### CODE REVIEW

**Comment by timoxley** [comment]
Tests ran successfully.

**Comment by timoxley** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by floatdrop** [comment]
Bump @chrisa.

**Comment by tjfontaine** [comment]
landed in 215af0c1117b12abe7c4e4a9482f34f53865a873

**Comment by tjfontaine** [comment]
published as 0.4.0

**Comment by ruimarinho** [comment]
Thanks! Bumped on bunyan. https://github.com/trentm/node-bunyan/pull/217

**Comment by floatdrop** [comment]
Thanks! :star2: :+1:

**Pull request closed without merging**
