### PR TITLE
Fixes #74: deprecation warnings when used with node v6.0.0

### LINKED ISSUE #74: deprecation warnings when used with node v6.0.0
Using dtrace-provider with node 6.0.0 (just released) gives numerous warnings likely because of the changes made to address nodejs/node#6216.

```
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x12bc086c9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x7c84e3227e4] (this=0x312e42fe1821 <an Object with map 0x2c26b8b5e91>#1#,module=0x229a538fbe9 <a Module with map 0x2c26b8181b9>#2#,filename=0x229a538fbb1 <String[115]: /Users/mdouglass/kixeye/km/server/kmservices/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node>)
    2: load [module.js:456] [pc=0x7c84df393b2] (this=0x229a538fbe9 <a Module with map 0x2c26b8181b9>#2#,filename=0x229a538fbb1 <String[115]: /Users/mdouglass/kixeye/km/server/kmservices/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x7c84df38edd] (this=0x12bc08604189 <undefined>,module=0x229a538fbe9 <a Module with map 0x2c26b8181b9>#2#,filename=0x229a538fbb1 <String[115]: /Users/mdouglass/kixeye/km/server/kmservices/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node>)
    4: _load [module.js:407] [pc=0x7c84df345e2] (this=0x312e42fe17d9 <JS Function Module (SharedFunctionInfo 0x312e42f28751)>#3#,request=0x229a538e2e9 <String[38]: ./build/Release/DTraceProviderBindings>,parent=0x229a538b641 <a Module with map 0x2c26b8181b9>#4#,isMain=0x12bc08604299 <false>)
2c26b8181b9>#4#,__filename=0x229a538b609 <String[92]: /Users/mdouglass/kixeye/km/server/kmservices/node_modules/dtrace-provider/dtrace-provider.js>,__dirname=0x229a538dc91 <String[73]: /Users/mdouglass/kixeye/km/server/kmservices/node_modules/dtrace-provider>)
    8: _compile [module.js:541] [pc=0x7c84df40b64] (this=0x229a538b641 <a Module with map 0x2c26b8181b9>#4#,content=0x229a538cce9 <Very long string[1202]>#7#,filename=0x229a538b609 <String[92]: /Users/mdouglass/kixeye/km/server/kmservices/node_modules/dtrace-provider/dtrace-provider.js>)
    9: /* anonymous */(aka /* anonymous */) [module.js:~548] [pc=0x7c84e05b824] (this=0x12bc08604189 <undefined>,module=0x229a538b641 <a Module with map 0x2c26b8181b9>#4#,filename=0x2s/mdouglass/kixeye/km/server/kmservices/lib/main.js:3] [pc=0x7c84e2accc6] (this=0x229a500de61 <an Object with map 0x1e30ece07b71>#21#,exports=0x229a500de61 <an Object with map 0x1e30ece07b71>#21#,require=0x229a500dc79 <JS Function require (SharedFunctionInfo 0x312e42f59d01)>#22#,module=0x229a500dbe9 <a Module with map 0x2c26b8181b9>#20#,__filename=0x229a500de11 <String[56]: /Users/mdouglass/kixeye/km/server/kmservices/lib/main.js>,__dirname=0x229a500dde9 <String[48]: /Users/mdouglass/kixeye/km/server/kmservices/lib>)
   45: _compile [module.js:541] [pc=0x7c84df40b64] (this=0x229a500dbe9 <a Module with map 0x2c26b8181b9>#20#,content=0x229a500f111 <Very long string[4605]>#23#,filename=0x229a500de11 <String[56]: /Users/mdouglass/kixeye/km/server/kmservices/lib/main.js>)
   46: loader(aka loader) [/Users/mdouglass/kixeye/km/server/kmservices/node_modules/babel-register/lib/node.js:126] [pc=0x7c84e1a00ff] (this=0x12bc08604189 <undefined>,m=0x229a500dbe9 <a Module with map 0x2c26b8181b9>#20#,filename=0x229a500de1
==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: node::DTraceProvider::Initialize(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 7: 0x7c84de0961b
 8: 0x7c84e3227e4
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.
```

### PR DESCRIPTION
**Pull request by jacargentina**
Updates nan to 2.3.3

### CODE REVIEW

**Comment by davepacheco** [comment]
Based on the comments in #74, I don't think this is actually necessary, though it also seems reasonable.

**Comment by ianvonholt** [comment]
I get similar depreciation warnings with dtrace-provider and Node v6.2.0.

Forking and upgrading nan to the latest 2.3.3 fixed all depreciation warning issues in OS X and Windows 10. 

+1 on upgrading the nan dependency.

**Comment by davepacheco** [comment]
@ianvonholt I don't think there's anything wrong with doing that, but I don't think that will actually help anybody unless they reinstall.  If they do reinstall, they'll already pick up 2.3.3 even without any changes to dtrace-provider's package.json.

**Comment by ianvonholt** [comment]
@davepacheco You are correct. It appears that some of my other packages where explicitly asking for nan 2.2.1 and the flat tree dependency resolution within npm was installing that. Sorry for the confusion!

**Comment by blai** [comment]
This is blocking the advancement to node 6 whenever you use some package like `mcavage/node-ldapjs`, which has a low level dependency on `chrisa/node-dtrace-provider`.

I also suggest we declare dependency to `"nan": "2"` (instead of `2.3.3`)

**Comment by davepacheco** [comment]
Thanks.  I went ahead and published version 0.7.0 with a fix for the case of higher-level dependencies (like the node-ldapjs case).  See my note in #74 for details.

**Pull request closed without merging**
