### PR TITLE
Upgrade to Nan 2 for iojs 3.x and node 4+ support

### PR DESCRIPTION
**Pull request by corbinu**
Upgraded nan and fixed all errors/warnings to prepare for 4+ support. 

I ran the test suite on OS X 10.10.5 and everything passed.

### CODE REVIEW

**Comment by corbinu** [comment]
Fixed for Node 0.12 on OS X and SmartOS

**Comment by davepacheco** [comment]
Thanks for doing this!  If one of the other maintainers doesn't get to it before me, I should be able to get to this by end-of-week.

**Comment by corbinu** [comment]
Thanks have also fixed for 0.10

**Comment by davepacheco** [comment]
@corbinu Thanks a lot for doing this!  The change LGTM.  Do you mind if I squash it into one commit (preserving the author, of course) before merging?

I only skimmed the delta, and it seems reasonable, but I'm not sure how the old constructs are supposed to map to the new ones.  Is there Nan documentation describing the changes that modules need to make to move to Nan 2?  It's surprising how much code had to change for that.

I ran the test suite on these platforms:

* SmartOS 20150818T191104Z, v0.12.7, ia32
* SmartOS 20150818T191104Z, v0.12.7, x64 
* SmartOS 20150818T191104Z, v0.10.40, ia32
* SmartOS 20150818T191104Z, v0.10.40, x64 
* OS X 10.8.5, v0.12.2, x64
* OS X 10.8.5, v0.10.28, x64

and all tests passed except for the two that get skipped on OS X (as expected).

**Comment by corbinu** [comment]
Your welcome to squash whatever is easiest for you. The closest thing to a Nan documentation on that I am pretty sure is this:

https://github.com/nodejs/nan/tree/master/tools

**Comment by davepacheco** [comment]
Landed this change, and published v0.6.0.  Thanks again!

**Pull request closed without merging**
